import { ACCOUNT_TRACKING_PREVENTION_PRESENCE_UPDATE_ALARM_NAME } from "./accountTrackingPrevention";
import { USER_ONLINE_FRIENDS_FETCH_ALARM_NAME } from "./friends";
import { SYNC_DATA_ALARM_NAME } from "./sync";

export const ALARMS = [
	SYNC_DATA_ALARM_NAME,
	USER_ONLINE_FRIENDS_FETCH_ALARM_NAME,
	ACCOUNT_TRACKING_PREVENTION_PRESENCE_UPDATE_ALARM_NAME,
];
