import { HOME_SORTS_LAYOUT_STORAGE_KEY } from "../components/home/layoutCustomization/constants";
import { FEATURE_STORAGE_KEY } from "../helpers/features/constants";
import { getLocalStorageKey } from "../helpers/storage";
import { getDelayKey } from "../utils/misc";
import {
	ACCOUNTS_RULES_SESSION_CACHE_STORAGE_KEY,
	ENCRYPTED_ACCOUNTS_STORAGE_KEY,
	LEGACY_MIZORE_ACCOUNTS_STORAGE_KEY,
	UNENCRYPTED_ACCOUNTS_STORAGE_KEY,
} from "./accountsManager";
import { AGREEMENTS_STORAGE_KEY, DISMISSED_ALERTS_STORAGE_KEY } from "./alerts";
import { API_KEYS_STORAGE_KEY } from "./apiKey";
import {
	AVATAR_ITEM_LISTS_STORAGE_KEY,
	BYPASS_R6_RESTRICTION_MODAL_LOCALSTORAGE_KEY,
} from "./avatar";
import { PRIVATE_NOTE_STORAGE_KEY } from "./experiences";
import {
	CONNECTIONS_TYPES_STORAGE_KEY,
	FRIENDS_LAST_SEEN_STORAGE_KEY,
	FRIENDS_PRESENCE_NOTIFICATIONS_DATA_STORAGE_KEY,
	FRIENDS_PRESENCE_NOTIFICATIONS_SESSION_CACHE_STORAGE_KEY,
	USER_ONLINE_FRIENDS_FETCHED_SESSION_CACHE_STORAGE_KEY,
} from "./friends";
import { GROUP_ORGANIZATION_STORAGE_KEY } from "./groupOrganization";
import { BIRTHDAYMESSAGE_DELAY_KEY } from "./home";
import { PREFERRED_LOCALES_STORAGE_KEY } from "./i18n";
import {
	ALLOWED_ITEMS_STORAGE_KEY,
	ARCHIVED_ITEMS_STORAGE_KEY,
	BLOCKED_ITEMS_STORAGE_KEY,
	LAUNCH_DATA_STORAGE_KEY,
	ONBOARDING_COMPLETED_STORAGE_KEY,
	PENDING_ROBUX_SESSION_CACHE_STORAGE_KEY,
	PERSIST_TRANSACTIONS_SELECTION_LOCALSTORAGE_KEY,
	PLUS_STATUS_BUTTON_ACKNOWLEDGED_LOCALSTORAGE_KEY,
	PREMIUM_MEMBERSHIP_STATUS_SESSION_CACHE_STORAGE_KEY,
	PREMIUM_STATUS_BUTTON_ACKNOWLEDGED_LOCALSTORAGE_KEY,
	ROBLOX_MEMBERSHIP_STATUS_SESSION_CACHE_STORAGE_KEY,
	ROBUX_HISTORY_STORAGE_KEY,
	STARTUP_NOTIFICATION_HAS_OPENED_ROBLOX_SESSION_STORAGE_KEY,
	UNIVERSES_SESSION_CACHE_STORAGE_KEY,
	UPCOMING_FOLLOWED_EVENTS_SESSION_CACHE_STORAGE_KEY,
	VERSION_STORAGE_KEY,
	VOICE_CHAT_SUSPENSION_STORAGE_KEY,
} from "./misc";
import { OAUTH_TOKENS_STORAGE_KEY } from "./oauth";
import { PRIVATE_SERVER_LINKS_STORAGE_KEY } from "./privateServerLinks";
import { EXPERIMENTS_DISCOVERED_STORAGE_KEY, EXPERIMENTS_STORAGE_KEY } from "./robloxExperiments";
import { USER_CHANNEL_DATA_SESSION_CACHE_STORAGE_KEY } from "./servers";
import { EXTENSION_INSTALLATION_ID_STORAGE_KEY } from "./sync";
import {
	TRADING_NOTIFICATIONS_FETCHED_SESSION_CACHE_STORAGE_KEY,
	TRADING_NOTIFICATIONS_STORAGE_KEY,
} from "./trades";

export const ALL_MAIN_STORAGE_KEYS = [
	VOICE_CHAT_SUSPENSION_STORAGE_KEY,
	BLOCKED_ITEMS_STORAGE_KEY,
	ALLOWED_ITEMS_STORAGE_KEY,
	LAUNCH_DATA_STORAGE_KEY,
	HOME_SORTS_LAYOUT_STORAGE_KEY,
	FEATURE_STORAGE_KEY,
	getDelayKey(BIRTHDAYMESSAGE_DELAY_KEY),
	PRIVATE_NOTE_STORAGE_KEY,
	UNENCRYPTED_ACCOUNTS_STORAGE_KEY,
	EXPERIMENTS_STORAGE_KEY,
	EXPERIMENTS_DISCOVERED_STORAGE_KEY,
	DISMISSED_ALERTS_STORAGE_KEY,
	AGREEMENTS_STORAGE_KEY,
	PREFERRED_LOCALES_STORAGE_KEY,
	PRIVATE_SERVER_LINKS_STORAGE_KEY,
	ONBOARDING_COMPLETED_STORAGE_KEY,
	EXTENSION_INSTALLATION_ID_STORAGE_KEY,
	VERSION_STORAGE_KEY,
	GROUP_ORGANIZATION_STORAGE_KEY,
	AVATAR_ITEM_LISTS_STORAGE_KEY,
	API_KEYS_STORAGE_KEY,
	OAUTH_TOKENS_STORAGE_KEY,
	ARCHIVED_ITEMS_STORAGE_KEY,
	ROBUX_HISTORY_STORAGE_KEY,
	FRIENDS_PRESENCE_NOTIFICATIONS_DATA_STORAGE_KEY,
	TRADING_NOTIFICATIONS_STORAGE_KEY,
	CONNECTIONS_TYPES_STORAGE_KEY,
];

export const ALL_SESSION_STORAGE_KEYS = [
	PENDING_ROBUX_SESSION_CACHE_STORAGE_KEY,
	UNIVERSES_SESSION_CACHE_STORAGE_KEY,
	UPCOMING_FOLLOWED_EVENTS_SESSION_CACHE_STORAGE_KEY,
	USER_CHANNEL_DATA_SESSION_CACHE_STORAGE_KEY,
	PREMIUM_MEMBERSHIP_STATUS_SESSION_CACHE_STORAGE_KEY,
	ROBLOX_MEMBERSHIP_STATUS_SESSION_CACHE_STORAGE_KEY,
	USER_ONLINE_FRIENDS_FETCHED_SESSION_CACHE_STORAGE_KEY,
	ACCOUNTS_RULES_SESSION_CACHE_STORAGE_KEY,
	STARTUP_NOTIFICATION_HAS_OPENED_ROBLOX_SESSION_STORAGE_KEY,
	TRADING_NOTIFICATIONS_FETCHED_SESSION_CACHE_STORAGE_KEY,
	FRIENDS_PRESENCE_NOTIFICATIONS_SESSION_CACHE_STORAGE_KEY,
];

export const ALL_LOCALSTORAGE_KEYS = [
	getLocalStorageKey(PERSIST_TRANSACTIONS_SELECTION_LOCALSTORAGE_KEY),
	getLocalStorageKey(PREFERRED_LOCALES_STORAGE_KEY),
	getLocalStorageKey(BYPASS_R6_RESTRICTION_MODAL_LOCALSTORAGE_KEY),
	getLocalStorageKey(PREMIUM_STATUS_BUTTON_ACKNOWLEDGED_LOCALSTORAGE_KEY),
	getLocalStorageKey(PLUS_STATUS_BUTTON_ACKNOWLEDGED_LOCALSTORAGE_KEY),
];

export const LEGACY_MAIN_UNMIGRATED_STORAGE_KEYS = [LEGACY_MIZORE_ACCOUNTS_STORAGE_KEY];
export const MAIN_UNMIGRATED_STORAGE_KEYS = [ENCRYPTED_ACCOUNTS_STORAGE_KEY];

export const MAIN_STORAGE_KEYS_SYNC = [
	ALLOWED_ITEMS_STORAGE_KEY,
	BLOCKED_ITEMS_STORAGE_KEY,
	HOME_SORTS_LAYOUT_STORAGE_KEY,
	FEATURE_STORAGE_KEY,
	PRIVATE_NOTE_STORAGE_KEY,
	PREFERRED_LOCALES_STORAGE_KEY,
	PRIVATE_SERVER_LINKS_STORAGE_KEY,
	GROUP_ORGANIZATION_STORAGE_KEY,
	FRIENDS_LAST_SEEN_STORAGE_KEY,
	AVATAR_ITEM_LISTS_STORAGE_KEY,
	ARCHIVED_ITEMS_STORAGE_KEY,
	ROBUX_HISTORY_STORAGE_KEY,
	CONNECTIONS_TYPES_STORAGE_KEY,
];
